# Generated by Django 5.0.2 on 2024-03-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0001_initial"),
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="tags",
            field=models.ManyToManyField(
                related_name="comments", through="tags.TagCommentSet", to="tags.tag"
            ),
        ),
    ]
